### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Sogl** [XristMisyris/quasar-starter-frontend#2]
Hello!

After `quasar dev` I see white page and some lines in console:

![image](https://cloud.githubusercontent.com/assets/7556290/26281787/57e1d3c4-3e4d-11e7-906a-ccd10394fd07.png)

I also see that now Quasar uses Vue2, but this app on Vue1.
Any chance to update?

**Comment by XristMisyris** [comment]
Updated on latest quasar version. I will update back end later today on Laravel 5.4

**Comment by Sogl** [comment]
Wow. Thx for your quick responce and fix!

You left your server name in code:

![image](https://cloud.githubusercontent.com/assets/7556290/26284343/56a83002-3e84-11e7-8370-d4a081b63e5f.png)

Can you handle such errors? Because after this error main window in infinite loading...
And how to switch view for desktop? Buttons is too loooooooong:
![image](https://cloud.githubusercontent.com/assets/7556290/26284363/b2f3f15c-3e84-11e7-9175-5946df4e5dff.png)

**Comment by Sogl** [comment]
>I will update back end later today on Laravel 5.4

Cool. I'm waiting 😉

**Comment by XristMisyris** [comment]
Updated back end https://github.com/XristMisyris/quasar-starter-backend

**Comment by XristMisyris** [comment]
#4 . This pull request will fix your errors. Thanks @colinmollenhour
